import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "index",
    "quick-start",
    {
      type: "category",
      label: "Installation",
      collapsed: true,
      items: [
        "installation/overview",
        "installation/zero-config",
        "installation/docker",
        "installation/verification",
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "guides/memory-management",
        "guides/memory-staleness",
        "guides/git-integration",
        "guides/code-expertise",
        "guides/context-building",
      ],
    },
    {
      type: "category",
      label: "Cookbook",
      collapsed: true,
      items: [
        "cookbook/architecture-decisions",
        "cookbook/bug-fix-solutions",
        "cookbook/code-patterns",
        "cookbook/team-workflows",
      ],
    },
    {
      type: "category",
      label: "API Reference",
      collapsed: false,
      items: [
        "api/overview",
        {
          type: "category",
          label: "Memory Tools",
          items: [
            "api/memory/store",
            "api/memory/search",
            "api/memory/get",
            "api/memory/update",
            "api/memory/delete",
          ],
        },
        {
          type: "category",
          label: "Memory Relations",
          items: [
            "api/relations/overview",
            "api/relations/link-memories",
            "api/relations/get-related",
            "api/relations/find-path",
            "api/relations/unlink-memories",
          ],
        },
        {
          type: "category",
          label: "Relation Detection",
          items: [
            "api/detection/overview",
            "api/detection/detect-relations",
            "api/detection/get-suggestions",
            "api/detection/review-suggestion",
            "api/detection/bulk-review",
          ],
        },
        {
          type: "category",
          label: "Cross-Layer Relations",
          items: [
            "api/cross-layer/overview",
            "api/cross-layer/suggest-crosslayer",
            "api/cross-layer/suggest-relations",
            "api/cross-layer/get-code-for-memory",
            "api/cross-layer/get-memories-for-code",
            "api/cross-layer/get-crosslayer-suggestions",
            "api/cross-layer/review-crosslayer",
            "api/cross-layer/bulk-review-crosslayer",
          ],
        },
        {
          type: "category",
          label: "Code Scanning (KAG)",
          items: [
            "api/code/overview",
            "api/code/scan-code",
            "api/code/stop-watch",
            "api/code/get-node",
            "api/code/call-graph",
            "api/code/impact-analysis",
            "api/code/find-implementations",
            "api/code/dependency-tree",
            "api/code/summarize",
            "api/code/update-code-summary",
            "api/code/get-unsummarized",
            "api/code/batch-update-summaries",
          ],
        },
        {
          type: "category",
          label: "Workflow & Approval",
          items: [
            "api/workflow/overview",
            "api/workflow/set-storage-mode",
            "api/workflow/get-storage-mode",
            "api/workflow/list-pending",
            "api/workflow/approve-pending",
            "api/workflow/reject-pending",
            "api/workflow/bulk-approve-pending",
            "api/workflow/bulk-reject-pending",
            "api/workflow/review-queue",
            "api/workflow/confirm-memory",
            "api/workflow/refresh-confidence",
          ],
        },
        {
          type: "category",
          label: "Context Building",
          items: ["api/context/overview", "api/context/build-context"],
        },
        {
          type: "category",
          label: "Token Budget",
          items: [
            "api/budget/overview",
            "api/budget/allocate-budget",
            "api/budget/model-windows",
            "api/budget/budget-presets",
          ],
        },
        {
          type: "category",
          label: "Export/Import",
          items: [
            "api/backup/overview",
            "api/backup/export",
            "api/backup/import",
          ],
        },
        {
          type: "category",
          label: "Cache & A/B Testing",
          items: [
            "api/testing/overview",
            "api/testing/cache-stats",
            "api/testing/cache-clear",
            "api/testing/experiment-status",
            "api/testing/experiment-metrics",
          ],
        },
        {
          type: "category",
          label: "Git Tools",
          items: [
            "api/git/commit-message",
            "api/git/pr-description",
            "api/git/changelog",
          ],
        },
        {
          type: "category",
          label: "Expertise Tools",
          items: ["api/expertise/mapping", "api/expertise/reviewers"],
        },
        {
          type: "category",
          label: "Bootstrap Tools",
          items: ["api/bootstrap/init"],
        },
        {
          type: "category",
          label: "Maintenance Tools",
          items: ["api/staleness/overview"],
        },
      ],
    },
    "configuration",
    {
      type: "category",
      label: "Architecture",
      collapsed: true,
      items: [
        "architecture/overview",
        "architecture/storage",
        "architecture/embeddings",
        {
          type: "category",
          label: "Chunking",
          collapsed: true,
          items: [
            "architecture/chunking/overview",
            "architecture/chunking/markdown",
            "architecture/chunking/code",
          ],
        },
        "architecture/vector-search",
        "architecture/retrieval-strategies",
        "architecture/confidence-decay",
      ],
    },
    "troubleshooting",
    "faq",
    "contributing",
  ],
};

export default sidebars;
